# prettier-ignore
name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  job1: 
    name: access-cloud-sql
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: 'SSH and deploy app'
      uses: appleboy/ssh-action@master
      with:
        instance_name: 'instance-1'
        zone: 'asia-southeast1-b'
        ssh_private_key: '${{ secrets.SSH_KEY }}'
        command: 'echo Hello world'
    
    - id: 'deploy-app'
      run: |
        ls -a
        gcloud compute instances describe 'instance-1' --zone=asia-southeast1-b --quiet
        git pull origin main
        npm install
        npm run migrate up
        pm2 restart forumapi
