# prettier-ignore
name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  job1: 
    name: access-cloud-sql
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
    
    - name: 'run gcloud access'
      run: 'gcloud compute ssh --zone "asia-southeast1-b" "instance-1" --project "ace-mile-409403"'
          
  job2:
    name: deploy
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: deploy app
        run: |
          cd ~/forumapi
          git pull origin main
          npm install
          npm run migrate up
          pm2 restart forumapi
